apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      nodePort: {{ .Values.service.NodePort}}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.app.name }}
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.postgres.port }}
  selector:
    app: postgres